/* ANSI-C code produced by gperf version 3.0.3 */
/* Command-line: gperf --key-positions='*' -D -n -s 2 CSSValueKeywords.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "CSSValueKeywords.gperf"

/* This file is automatically generated from CSSValueKeywords.in by makevalues, do not edit */

#include "CSSValueKeywords.h"
#line 7 "CSSValueKeywords.gperf"
struct Value {
    const char* name;
    int id;
};
#include <string.h>
/* maximum key range = 5608, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
value_hash_function (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613,  320,  680, 5613,   20,    5,
        80,   40,   15,    0,   75,   70,   45,   25, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613,   20,   75,  175,
       785,    0,  180,   11,  895,   15,    1,  240,   25,   40,
        10,   35,  515,   51,    5,   30,    0,  240,   51,  331,
      1020,  981,  920, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613, 5613,
      5613, 5613, 5613, 5613, 5613, 5613, 5613
    };
  register int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[(unsigned char)str[34]];
      /*FALLTHROUGH*/
      case 34:
        hval += asso_values[(unsigned char)str[33]];
      /*FALLTHROUGH*/
      case 33:
        hval += asso_values[(unsigned char)str[32]];
      /*FALLTHROUGH*/
      case 32:
        hval += asso_values[(unsigned char)str[31]];
      /*FALLTHROUGH*/
      case 31:
        hval += asso_values[(unsigned char)str[30]];
      /*FALLTHROUGH*/
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]+1];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]+1];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#ifdef __GNUC_STDC_INLINE__
__attribute__ ((__gnu_inline__))
#endif
#endif
const struct Value *
findValue (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 474,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 35,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 5612
    };

  static const struct Value value_word_list[] =
    {
#line 96 "CSSValueKeywords.gperf"
      {"red", CSSValueRed},
#line 362 "CSSValueKeywords.gperf"
      {"end", CSSValueEnd},
#line 310 "CSSValueKeywords.gperf"
      {"a5", CSSValueA5},
#line 53 "CSSValueKeywords.gperf"
      {"500", CSSValue500},
#line 49 "CSSValueKeywords.gperf"
      {"100", CSSValue100},
#line 309 "CSSValueKeywords.gperf"
      {"a4", CSSValueA4},
#line 52 "CSSValueKeywords.gperf"
      {"400", CSSValue400},
#line 302 "CSSValueKeywords.gperf"
      {"rtl", CSSValueRtl},
#line 57 "CSSValueKeywords.gperf"
      {"900", CSSValue900},
#line 301 "CSSValueKeywords.gperf"
      {"ltr", CSSValueLtr},
#line 378 "CSSValueKeywords.gperf"
      {"slide", CSSValueSlide},
#line 308 "CSSValueKeywords.gperf"
      {"a3", CSSValueA3},
#line 400 "CSSValueKeywords.gperf"
      {"radio", CSSValueRadio},
#line 377 "CSSValueKeywords.gperf"
      {"infinite", CSSValueInfinite},
#line 51 "CSSValueKeywords.gperf"
      {"300", CSSValue300},
#line 56 "CSSValueKeywords.gperf"
      {"800", CSSValue800},
#line 316 "CSSValueKeywords.gperf"
      {"b5", CSSValueB5},
#line 248 "CSSValueKeywords.gperf"
      {"inline", CSSValueInline},
#line 154 "CSSValueKeywords.gperf"
      {"middle", CSSValueMiddle},
#line 43 "CSSValueKeywords.gperf"
      {"all", CSSValueAll},
#line 159 "CSSValueKeywords.gperf"
      {"top", CSSValueTop},
#line 315 "CSSValueKeywords.gperf"
      {"b4", CSSValueB4},
#line 55 "CSSValueKeywords.gperf"
      {"700", CSSValue700},
#line 54 "CSSValueKeywords.gperf"
      {"600", CSSValue600},
#line 50 "CSSValueKeywords.gperf"
      {"200", CSSValue200},
#line 337 "CSSValueKeywords.gperf"
      {"loud", CSSValueLoud},
#line 98 "CSSValueKeywords.gperf"
      {"teal", CSSValueTeal},
#line 34 "CSSValueKeywords.gperf"
      {"menu", CSSValueMenu},
#line 45 "CSSValueKeywords.gperf"
      {"normal", CSSValueNormal},
#line 361 "CSSValueKeywords.gperf"
      {"start", CSSValueStart},
#line 454 "CSSValueKeywords.gperf"
      {"border", CSSValueBorder},
#line 46 "CSSValueKeywords.gperf"
      {"bold", CSSValueBold},
#line 275 "CSSValueKeywords.gperf"
      {"alias", CSSValueAlias},
#line 47 "CSSValueKeywords.gperf"
      {"bolder", CSSValueBolder},
#line 94 "CSSValueKeywords.gperf"
      {"orange", CSSValueOrange},
#line 463 "CSSValueKeywords.gperf"
      {"visual", CSSValueVisual},
#line 306 "CSSValueKeywords.gperf"
      {"visible", CSSValueVisible},
#line 224 "CSSValueKeywords.gperf"
      {"sidama", CSSValueSidama},
#line 353 "CSSValueKeywords.gperf"
      {"separate", CSSValueSeparate},
#line 475 "CSSValueKeywords.gperf"
      {"reset", CSSValueReset},
#line 351 "CSSValueKeywords.gperf"
      {"relative", CSSValueRelative},
#line 226 "CSSValueKeywords.gperf"
      {"somali", CSSValueSomali},
#line 493 "CSSValueKeywords.gperf"
      {"manual", CSSValueManual},
#line 428 "CSSValueKeywords.gperf"
      {"menulist", CSSValueMenulist},
#line 84 "CSSValueKeywords.gperf"
      {"aqua", CSSValueAqua},
#line 469 "CSSValueKeywords.gperf"
      {"ease", CSSValueEase},
#line 24 "CSSValueKeywords.gperf"
      {"inset", CSSValueInset},
#line 60 "CSSValueKeywords.gperf"
      {"small", CSSValueSmall},
#line 174 "CSSValueKeywords.gperf"
      {"square", CSSValueSquare},
#line 66 "CSSValueKeywords.gperf"
      {"smaller", CSSValueSmaller},
#line 383 "CSSValueKeywords.gperf"
      {"element", CSSValueElement},
#line 90 "CSSValueKeywords.gperf"
      {"lime", CSSValueLime},
#line 254 "CSSValueKeywords.gperf"
      {"table", CSSValueTable},
#line 20 "CSSValueKeywords.gperf"
      {"inherit", CSSValueInherit},
#line 78 "CSSValueKeywords.gperf"
      {"serif", CSSValueSerif},
#line 387 "CSSValueKeywords.gperf"
      {"clip", CSSValueClip},
#line 273 "CSSValueKeywords.gperf"
      {"cell", CSSValueCell},
#line 136 "CSSValueKeywords.gperf"
      {"repeat", CSSValueRepeat},
#line 22 "CSSValueKeywords.gperf"
      {"none", CSSValueNone},
#line 241 "CSSValueKeywords.gperf"
      {"armenian", CSSValueArmenian},
#line 480 "CSSValueKeywords.gperf"
      {"fill", CSSValueFill},
#line 163 "CSSValueKeywords.gperf"
      {"left", CSSValueLeft},
#line 470 "CSSValueKeywords.gperf"
      {"linear", CSSValueLinear},
#line 464 "CSSValueKeywords.gperf"
      {"lines", CSSValueLines},
#line 194 "CSSValueKeywords.gperf"
      {"urdu", CSSValueUrdu},
#line 206 "CSSValueKeywords.gperf"
      {"afar", CSSValueAfar},
#line 41 "CSSValueKeywords.gperf"
      {"italic", CSSValueItalic},
#line 61 "CSSValueKeywords.gperf"
      {"medium", CSSValueMedium},
#line 153 "CSSValueKeywords.gperf"
      {"baseline", CSSValueBaseline},
#line 21 "CSSValueKeywords.gperf"
      {"initial", CSSValueInitial},
#line 86 "CSSValueKeywords.gperf"
      {"blue", CSSValueBlue},
#line 410 "CSSValueKeywords.gperf"
      {"listitem", CSSValueListitem},
#line 195 "CSSValueKeywords.gperf"
      {"telugu", CSSValueTelugu},
#line 209 "CSSValueKeywords.gperf"
      {"amharic", CSSValueAmharic},
#line 346 "CSSValueKeywords.gperf"
      {"overline", CSSValueOverline},
#line 465 "CSSValueKeywords.gperf"
      {"running", CSSValueRunning},
#line 320 "CSSValueKeywords.gperf"
      {"both", CSSValueBoth},
#line 319 "CSSValueKeywords.gperf"
      {"blink", CSSValueBlink},
#line 89 "CSSValueKeywords.gperf"
      {"green", CSSValueGreen},
#line 93 "CSSValueKeywords.gperf"
      {"olive", CSSValueOlive},
#line 196 "CSSValueKeywords.gperf"
      {"tibetan", CSSValueTibetan},
#line 440 "CSSValueKeywords.gperf"
      {"caret", CSSValueCaret},
#line 477 "CSSValueKeywords.gperf"
      {"visiblefill", CSSValueVisiblefill},
#line 97 "CSSValueKeywords.gperf"
      {"silver", CSSValueSilver},
#line 376 "CSSValueKeywords.gperf"
      {"fast", CSSValueFast},
#line 42 "CSSValueKeywords.gperf"
      {"oblique", CSSValueOblique},
#line 155 "CSSValueKeywords.gperf"
      {"sub", CSSValueSub},
#line 165 "CSSValueKeywords.gperf"
      {"center", CSSValueCenter},
#line 140 "CSSValueKeywords.gperf"
      {"clear", CSSValueClear},
#line 69 "CSSValueKeywords.gperf"
      {"narrower", CSSValueNarrower},
#line 432 "CSSValueKeywords.gperf"
      {"meter", CSSValueMeter},
#line 252 "CSSValueKeywords.gperf"
      {"compact", CSSValueCompact},
#line 478 "CSSValueKeywords.gperf"
      {"visiblestroke", CSSValueVisiblestroke},
#line 358 "CSSValueKeywords.gperf"
      {"underline", CSSValueUnderline},
#line 456 "CSSValueKeywords.gperf"
      {"content", CSSValueContent},
#line 379 "CSSValueKeywords.gperf"
      {"alternate", CSSValueAlternate},
#line 156 "CSSValueKeywords.gperf"
      {"super", CSSValueSuper},
#line 333 "CSSValueKeywords.gperf"
      {"letter", CSSValueLetter},
#line 80 "CSSValueKeywords.gperf"
      {"cursive", CSSValueCursive},
#line 27 "CSSValueKeywords.gperf"
      {"outset", CSSValueOutset},
#line 255 "CSSValueKeywords.gperf"
      {"inline-table", CSSValueInlineTable},
#line 467 "CSSValueKeywords.gperf"
      {"flat", CSSValueFlat},
#line 460 "CSSValueKeywords.gperf"
      {"contain", CSSValueContain},
#line 68 "CSSValueKeywords.gperf"
      {"wider", CSSValueWider},
#line 355 "CSSValueKeywords.gperf"
      {"static", CSSValueStatic},
#line 385 "CSSValueKeywords.gperf"
      {"intrinsic", CSSValueIntrinsic},
#line 329 "CSSValueKeywords.gperf"
      {"invert", CSSValueInvert},
#line 471 "CSSValueKeywords.gperf"
      {"ease-in", CSSValueEaseIn},
#line 32 "CSSValueKeywords.gperf"
      {"caption", CSSValueCaption},
#line 191 "CSSValueKeywords.gperf"
      {"octal", CSSValueOctal},
#line 363 "CSSValueKeywords.gperf"
      {"reverse", CSSValueReverse},
#line 365 "CSSValueKeywords.gperf"
      {"vertical", CSSValueVertical},
#line 187 "CSSValueKeywords.gperf"
      {"lao", CSSValueLao},
#line 334 "CSSValueKeywords.gperf"
      {"level", CSSValueLevel},
#line 458 "CSSValueKeywords.gperf"
      {"padding", CSSValuePadding},
#line 384 "CSSValueKeywords.gperf"
      {"ignore", CSSValueIgnore},
#line 271 "CSSValueKeywords.gperf"
      {"move", CSSValueMove},
#line 193 "CSSValueKeywords.gperf"
      {"persian", CSSValuePersian},
#line 270 "CSSValueKeywords.gperf"
      {"pointer", CSSValuePointer},
#line 296 "CSSValueKeywords.gperf"
      {"wait", CSSValueWait},
#line 222 "CSSValueKeywords.gperf"
      {"oromo", CSSValueOromo},
#line 183 "CSSValueKeywords.gperf"
      {"gujarati", CSSValueGujarati},
#line 242 "CSSValueKeywords.gperf"
      {"georgian", CSSValueGeorgian},
#line 79 "CSSValueKeywords.gperf"
      {"sans-serif", CSSValueSansSerif},
#line 91 "CSSValueKeywords.gperf"
      {"maroon", CSSValueMaroon},
#line 250 "CSSValueKeywords.gperf"
      {"list-item", CSSValueListItem},
#line 388 "CSSValueKeywords.gperf"
      {"ellipsis", CSSValueEllipsis},
#line 160 "CSSValueKeywords.gperf"
      {"bottom", CSSValueBottom},
#line 143 "CSSValueKeywords.gperf"
      {"source-in", CSSValueSourceIn},
#line 437 "CSSValueKeywords.gperf"
      {"slider-vertical", CSSValueSliderVertical},
#line 101 "CSSValueKeywords.gperf"
      {"transparent", CSSValueTransparent},
#line 348 "CSSValueKeywords.gperf"
      {"pre", CSSValuePre},
#line 489 "CSSValueKeywords.gperf"
      {"fullscreen", CSSValueFullscreen},
#line 323 "CSSValueKeywords.gperf"
      {"cross", CSSValueCross},
#line 461 "CSSValueKeywords.gperf"
      {"cover", CSSValueCover},
#line 142 "CSSValueKeywords.gperf"
      {"source-over", CSSValueSourceOver},
#line 33 "CSSValueKeywords.gperf"
      {"icon", CSSValueIcon},
#line 322 "CSSValueKeywords.gperf"
      {"crop", CSSValueCrop},
#line 129 "CSSValueKeywords.gperf"
      {"window", CSSValueWindow},
#line 381 "CSSValueKeywords.gperf"
      {"read-write", CSSValueReadWrite},
#line 373 "CSSValueKeywords.gperf"
      {"up", CSSValueUp},
#line 215 "CSSValueKeywords.gperf"
      {"ethiopic", CSSValueEthiopic},
#line 133 "CSSValueKeywords.gperf"
      {"currentcolor", CSSValueCurrentcolor},
#line 262 "CSSValueKeywords.gperf"
      {"table-cell", CSSValueTableCell},
#line 472 "CSSValueKeywords.gperf"
      {"ease-out", CSSValueEaseOut},
#line 352 "CSSValueKeywords.gperf"
      {"scroll", CSSValueScroll},
#line 171 "CSSValueKeywords.gperf"
      {"inside", CSSValueInside},
#line 481 "CSSValueKeywords.gperf"
      {"stroke", CSSValueStroke},
#line 330 "CSSValueKeywords.gperf"
      {"landscape", CSSValueLandscape},
#line 488 "CSSValueKeywords.gperf"
      {"floating", CSSValueFloating},
#line 403 "CSSValueKeywords.gperf"
      {"button", CSSValueButton},
#line 307 "CSSValueKeywords.gperf"
      {"collapse", CSSValueCollapse},
#line 347 "CSSValueKeywords.gperf"
      {"portrait", CSSValuePortrait},
#line 95 "CSSValueKeywords.gperf"
      {"purple", CSSValuePurple},
#line 392 "CSSValueKeywords.gperf"
      {"wave", CSSValueWave},
#line 245 "CSSValueKeywords.gperf"
      {"katakana", CSSValueKatakana},
#line 312 "CSSValueKeywords.gperf"
      {"absolute", CSSValueAbsolute},
#line 429 "CSSValueKeywords.gperf"
      {"menulist-button", CSSValueMenulistButton},
#line 30 "CSSValueKeywords.gperf"
      {"solid", CSSValueSolid},
#line 402 "CSSValueKeywords.gperf"
      {"square-button", CSSValueSquareButton},
#line 123 "CSSValueKeywords.gperf"
      {"scrollbar", CSSValueScrollbar},
#line 453 "CSSValueKeywords.gperf"
      {"round", CSSValueRound},
#line 26 "CSSValueKeywords.gperf"
      {"ridge", CSSValueRidge},
#line 144 "CSSValueKeywords.gperf"
      {"source-out", CSSValueSourceOut},
#line 23 "CSSValueKeywords.gperf"
      {"hidden", CSSValueHidden},
#line 331 "CSSValueKeywords.gperf"
      {"ledger", CSSValueLedger},
#line 259 "CSSValueKeywords.gperf"
      {"table-row", CSSValueTableRow},
#line 164 "CSSValueKeywords.gperf"
      {"right", CSSValueRight},
#line 357 "CSSValueKeywords.gperf"
      {"thin", CSSValueThin},
#line 228 "CSSValueKeywords.gperf"
      {"tigre", CSSValueTigre},
#line 311 "CSSValueKeywords.gperf"
      {"above", CSSValueAbove},
#line 336 "CSSValueKeywords.gperf"
      {"local", CSSValueLocal},
#line 253 "CSSValueKeywords.gperf"
      {"inline-block", CSSValueInlineBlock},
#line 326 "CSSValueKeywords.gperf"
      {"hand", CSSValueHand},
#line 48 "CSSValueKeywords.gperf"
      {"lighter", CSSValueLighter},
#line 408 "CSSValueKeywords.gperf"
      {"list-button", CSSValueListButton},
#line 317 "CSSValueKeywords.gperf"
      {"below", CSSValueBelow},
#line 395 "CSSValueKeywords.gperf"
      {"break-all", CSSValueBreakAll},
#line 62 "CSSValueKeywords.gperf"
      {"large", CSSValueLarge},
#line 197 "CSSValueKeywords.gperf"
      {"thai", CSSValueThai},
#line 67 "CSSValueKeywords.gperf"
      {"larger", CSSValueLarger},
#line 192 "CSSValueKeywords.gperf"
      {"oriya", CSSValueOriya},
#line 251 "CSSValueKeywords.gperf"
      {"run-in", CSSValueRunIn},
#line 297 "CSSValueKeywords.gperf"
      {"help", CSSValueHelp},
#line 130 "CSSValueKeywords.gperf"
      {"windowframe", CSSValueWindowframe},
#line 368 "CSSValueKeywords.gperf"
      {"single", CSSValueSingle},
#line 88 "CSSValueKeywords.gperf"
      {"gray", CSSValueGray},
#line 267 "CSSValueKeywords.gperf"
      {"auto", CSSValueAuto},
#line 332 "CSSValueKeywords.gperf"
      {"legal", CSSValueLegal},
#line 173 "CSSValueKeywords.gperf"
      {"circle", CSSValueCircle},
#line 40 "CSSValueKeywords.gperf"
      {"status-bar", CSSValueStatusBar},
#line 340 "CSSValueKeywords.gperf"
      {"mix", CSSValueMix},
#line 386 "CSSValueKeywords.gperf"
      {"min-intrinsic", CSSValueMinIntrinsic},
#line 393 "CSSValueKeywords.gperf"
      {"continuous", CSSValueContinuous},
#line 298 "CSSValueKeywords.gperf"
      {"all-scroll", CSSValueAllScroll},
#line 179 "CSSValueKeywords.gperf"
      {"bengali", CSSValueBengali},
#line 72 "CSSValueKeywords.gperf"
      {"condensed", CSSValueCondensed},
#line 31 "CSSValueKeywords.gperf"
      {"double", CSSValueDouble},
#line 244 "CSSValueKeywords.gperf"
      {"hiragana", CSSValueHiragana},
#line 261 "CSSValueKeywords.gperf"
      {"table-column", CSSValueTableColumn},
#line 150 "CSSValueKeywords.gperf"
      {"xor", CSSValueXor},
#line 327 "CSSValueKeywords.gperf"
      {"hide", CSSValueHide},
#line 25 "CSSValueKeywords.gperf"
      {"groove", CSSValueGroove},
#line 487 "CSSValueKeywords.gperf"
      {"srgb", CSSValueSrgb},
#line 189 "CSSValueKeywords.gperf"
      {"mongolian", CSSValueMongolian},
#line 369 "CSSValueKeywords.gperf"
      {"multiple", CSSValueMultiple},
#line 134 "CSSValueKeywords.gperf"
      {"grey", CSSValueGrey},
#line 269 "CSSValueKeywords.gperf"
      {"default", CSSValueDefault},
#line 473 "CSSValueKeywords.gperf"
      {"ease-in-out", CSSValueEaseInOut},
#line 122 "CSSValueKeywords.gperf"
      {"menutext", CSSValueMenutext},
#line 185 "CSSValueKeywords.gperf"
      {"kannada", CSSValueKannada},
#line 482 "CSSValueKeywords.gperf"
      {"antialiased", CSSValueAntialiased},
#line 462 "CSSValueKeywords.gperf"
      {"logical", CSSValueLogical},
#line 324 "CSSValueKeywords.gperf"
      {"embed", CSSValueEmbed},
#line 141 "CSSValueKeywords.gperf"
      {"copy", CSSValueCopy},
#line 178 "CSSValueKeywords.gperf"
      {"binary", CSSValueBinary},
#line 190 "CSSValueKeywords.gperf"
      {"myanmar", CSSValueMyanmar},
#line 85 "CSSValueKeywords.gperf"
      {"black", CSSValueBlack},
#line 145 "CSSValueKeywords.gperf"
      {"source-atop", CSSValueSourceAtop},
#line 108 "CSSValueKeywords.gperf"
      {"buttonface", CSSValueButtonface},
#line 304 "CSSValueKeywords.gperf"
      {"uppercase", CSSValueUppercase},
#line 295 "CSSValueKeywords.gperf"
      {"text", CSSValueText},
#line 303 "CSSValueKeywords.gperf"
      {"capitalize", CSSValueCapitalize},
#line 419 "CSSValueKeywords.gperf"
      {"media-slider", CSSValueMediaSlider},
#line 180 "CSSValueKeywords.gperf"
      {"cambodian", CSSValueCambodian},
#line 105 "CSSValueKeywords.gperf"
      {"activecaption", CSSValueActivecaption},
#line 188 "CSSValueKeywords.gperf"
      {"malayalam", CSSValueMalayalam},
#line 338 "CSSValueKeywords.gperf"
      {"lower", CSSValueLower},
#line 452 "CSSValueKeywords.gperf"
      {"textarea", CSSValueTextarea},
#line 44 "CSSValueKeywords.gperf"
      {"small-caps", CSSValueSmallCaps},
#line 182 "CSSValueKeywords.gperf"
      {"devanagari", CSSValueDevanagari},
#line 277 "CSSValueKeywords.gperf"
      {"no-drop", CSSValueNoDrop},
#line 92 "CSSValueKeywords.gperf"
      {"navy", CSSValueNavy},
#line 87 "CSSValueKeywords.gperf"
      {"fuchsia", CSSValueFuchsia},
#line 139 "CSSValueKeywords.gperf"
      {"no-repeat", CSSValueNoRepeat},
#line 36 "CSSValueKeywords.gperf"
      {"small-caption", CSSValueSmallCaption},
#line 318 "CSSValueKeywords.gperf"
      {"bidi-override", CSSValueBidiOverride},
#line 360 "CSSValueKeywords.gperf"
      {"stretch", CSSValueStretch},
#line 404 "CSSValueKeywords.gperf"
      {"button-bevel", CSSValueButtonBevel},
#line 170 "CSSValueKeywords.gperf"
      {"outside", CSSValueOutside},
#line 345 "CSSValueKeywords.gperf"
      {"overlay", CSSValueOverlay},
#line 263 "CSSValueKeywords.gperf"
      {"table-caption", CSSValueTableCaption},
#line 181 "CSSValueKeywords.gperf"
      {"khmer", CSSValueKhmer},
#line 412 "CSSValueKeywords.gperf"
      {"media-mute-button", CSSValueMediaMuteButton},
#line 479 "CSSValueKeywords.gperf"
      {"painted", CSSValuePainted},
#line 321 "CSSValueKeywords.gperf"
      {"close-quote", CSSValueCloseQuote},
#line 82 "CSSValueKeywords.gperf"
      {"monospace", CSSValueMonospace},
#line 466 "CSSValueKeywords.gperf"
      {"paused", CSSValuePaused},
#line 314 "CSSValueKeywords.gperf"
      {"avoid", CSSValueAvoid},
#line 205 "CSSValueKeywords.gperf"
      {"upper-latin", CSSValueUpperLatin},
#line 104 "CSSValueKeywords.gperf"
      {"activeborder", CSSValueActiveborder},
#line 397 "CSSValueKeywords.gperf"
      {"space", CSSValueSpace},
#line 409 "CSSValueKeywords.gperf"
      {"listbox", CSSValueListbox},
#line 344 "CSSValueKeywords.gperf"
      {"open-quote", CSSValueOpenQuote},
#line 59 "CSSValueKeywords.gperf"
      {"x-small", CSSValueXSmall},
#line 200 "CSSValueKeywords.gperf"
      {"upper-roman", CSSValueUpperRoman},
#line 100 "CSSValueKeywords.gperf"
      {"yellow", CSSValueYellow},
#line 349 "CSSValueKeywords.gperf"
      {"pre-line", CSSValuePreLine},
#line 240 "CSSValueKeywords.gperf"
      {"hebrew", CSSValueHebrew},
#line 401 "CSSValueKeywords.gperf"
      {"push-button", CSSValuePushButton},
#line 380 "CSSValueKeywords.gperf"
      {"read-only", CSSValueReadOnly},
#line 266 "CSSValueKeywords.gperf"
      {"-wap-marquee", CSSValueWapMarquee},
#line 99 "CSSValueKeywords.gperf"
      {"white", CSSValueWhite},
#line 63 "CSSValueKeywords.gperf"
      {"x-large", CSSValueXLarge},
#line 147 "CSSValueKeywords.gperf"
      {"destination-in", CSSValueDestinationIn},
#line 366 "CSSValueKeywords.gperf"
      {"inline-axis", CSSValueInlineAxis},
#line 305 "CSSValueKeywords.gperf"
      {"lowercase", CSSValueLowercase},
#line 281 "CSSValueKeywords.gperf"
      {"e-resize", CSSValueEResize},
#line 284 "CSSValueKeywords.gperf"
      {"n-resize", CSSValueNResize},
#line 81 "CSSValueKeywords.gperf"
      {"fantasy", CSSValueFantasy},
#line 476 "CSSValueKeywords.gperf"
      {"visiblepainted", CSSValueVisiblepainted},
#line 35 "CSSValueKeywords.gperf"
      {"message-box", CSSValueMessageBox},
#line 287 "CSSValueKeywords.gperf"
      {"s-resize", CSSValueSResize},
#line 486 "CSSValueKeywords.gperf"
      {"geometricprecision", CSSValueGeometricprecision},
#line 492 "CSSValueKeywords.gperf"
      {"windowed", CSSValueWindowed},
#line 430 "CSSValueKeywords.gperf"
      {"menulist-text", CSSValueMenulistText},
#line 146 "CSSValueKeywords.gperf"
      {"destination-over", CSSValueDestinationOver},
#line 211 "CSSValueKeywords.gperf"
      {"amharic-abegede", CSSValueAmharicAbegede},
#line 138 "CSSValueKeywords.gperf"
      {"repeat-y", CSSValueRepeatY},
#line 112 "CSSValueKeywords.gperf"
      {"captiontext", CSSValueCaptiontext},
#line 238 "CSSValueKeywords.gperf"
      {"upper-greek", CSSValueUpperGreek},
#line 120 "CSSValueKeywords.gperf"
      {"infotext", CSSValueInfotext},
#line 172 "CSSValueKeywords.gperf"
      {"disc", CSSValueDisc},
#line 375 "CSSValueKeywords.gperf"
      {"slow", CSSValueSlow},
#line 455 "CSSValueKeywords.gperf"
      {"border-box", CSSValueBorderBox},
#line 137 "CSSValueKeywords.gperf"
      {"repeat-x", CSSValueRepeatX},
#line 29 "CSSValueKeywords.gperf"
      {"dashed", CSSValueDashed},
#line 343 "CSSValueKeywords.gperf"
      {"nowrap", CSSValueNowrap},
#line 249 "CSSValueKeywords.gperf"
      {"block", CSSValueBlock},
#line 203 "CSSValueKeywords.gperf"
      {"lower-latin", CSSValueLowerLatin},
#line 175 "CSSValueKeywords.gperf"
      {"decimal", CSSValueDecimal},
#line 166 "CSSValueKeywords.gperf"
      {"justify", CSSValueJustify},
#line 268 "CSSValueKeywords.gperf"
      {"crosshair", CSSValueCrosshair},
#line 184 "CSSValueKeywords.gperf"
      {"gurmukhi", CSSValueGurmukhi},
#line 282 "CSSValueKeywords.gperf"
      {"ne-resize", CSSValueNeResize},
#line 299 "CSSValueKeywords.gperf"
      {"-webkit-grab", CSSValueWebkitGrab},
#line 199 "CSSValueKeywords.gperf"
      {"lower-roman", CSSValueLowerRoman},
#line 285 "CSSValueKeywords.gperf"
      {"se-resize", CSSValueSeResize},
#line 474 "CSSValueKeywords.gperf"
      {"document", CSSValueDocument},
#line 290 "CSSValueKeywords.gperf"
      {"ns-resize", CSSValueNsResize},
#line 117 "CSSValueKeywords.gperf"
      {"inactivecaption", CSSValueInactivecaption},
#line 148 "CSSValueKeywords.gperf"
      {"destination-out", CSSValueDestinationOut},
#line 158 "CSSValueKeywords.gperf"
      {"text-bottom", CSSValueTextBottom},
#line 239 "CSSValueKeywords.gperf"
      {"upper-norwegian", CSSValueUpperNorwegian},
#line 411 "CSSValueKeywords.gperf"
      {"media-fullscreen-button", CSSValueMediaFullscreenButton},
#line 131 "CSSValueKeywords.gperf"
      {"windowtext", CSSValueWindowtext},
#line 169 "CSSValueKeywords.gperf"
      {"-webkit-center", CSSValueWebkitCenter},
#line 177 "CSSValueKeywords.gperf"
      {"arabic-indic", CSSValueArabicIndic},
#line 167 "CSSValueKeywords.gperf"
      {"-webkit-left", CSSValueWebkitLeft},
#line 300 "CSSValueKeywords.gperf"
      {"-webkit-grabbing", CSSValueWebkitGrabbing},
#line 292 "CSSValueKeywords.gperf"
      {"nwse-resize", CSSValueNwseResize},
#line 406 "CSSValueKeywords.gperf"
      {"inner-spin-button", CSSValueInnerSpinButton},
#line 405 "CSSValueKeywords.gperf"
      {"default-button", CSSValueDefaultButton},
#line 328 "CSSValueKeywords.gperf"
      {"higher", CSSValueHigher},
#line 288 "CSSValueKeywords.gperf"
      {"w-resize", CSSValueWResize},
#line 201 "CSSValueKeywords.gperf"
      {"lower-greek", CSSValueLowerGreek},
#line 491 "CSSValueKeywords.gperf"
      {"minimized", CSSValueMinimized},
#line 116 "CSSValueKeywords.gperf"
      {"inactiveborder", CSSValueInactiveborder},
#line 111 "CSSValueKeywords.gperf"
      {"buttontext", CSSValueButtontext},
#line 152 "CSSValueKeywords.gperf"
      {"plus-lighter", CSSValuePlusLighter},
#line 39 "CSSValueKeywords.gperf"
      {"-webkit-control", CSSValueWebkitControl},
#line 102 "CSSValueKeywords.gperf"
      {"-webkit-link", CSSValueWebkitLink},
#line 374 "CSSValueKeywords.gperf"
      {"down", CSSValueDown},
#line 162 "CSSValueKeywords.gperf"
      {"-webkit-auto", CSSValueWebkitAuto},
#line 272 "CSSValueKeywords.gperf"
      {"vertical-text", CSSValueVerticalText},
#line 293 "CSSValueKeywords.gperf"
      {"col-resize", CSSValueColResize},
#line 468 "CSSValueKeywords.gperf"
      {"preserve-3d", CSSValuePreserve3d},
#line 356 "CSSValueKeywords.gperf"
      {"thick", CSSValueThick},
#line 439 "CSSValueKeywords.gperf"
      {"sliderthumb-vertical", CSSValueSliderthumbVertical},
#line 258 "CSSValueKeywords.gperf"
      {"table-footer-group", CSSValueTableFooterGroup},
#line 339 "CSSValueKeywords.gperf"
      {"-webkit-marquee", CSSValueWebkitMarquee},
#line 457 "CSSValueKeywords.gperf"
      {"content-box", CSSValueContentBox},
#line 422 "CSSValueKeywords.gperf"
      {"media-volume-slider", CSSValueMediaVolumeSlider},
#line 372 "CSSValueKeywords.gperf"
      {"ahead", CSSValueAhead},
#line 151 "CSSValueKeywords.gperf"
      {"plus-darker", CSSValuePlusDarker},
#line 217 "CSSValueKeywords.gperf"
      {"ethiopic-abegede", CSSValueEthiopicAbegede},
#line 364 "CSSValueKeywords.gperf"
      {"horizontal", CSSValueHorizontal},
#line 121 "CSSValueKeywords.gperf"
      {"match", CSSValueMatch},
#line 107 "CSSValueKeywords.gperf"
      {"background", CSSValueBackground},
#line 276 "CSSValueKeywords.gperf"
      {"progress", CSSValueProgress},
#line 289 "CSSValueKeywords.gperf"
      {"ew-resize", CSSValueEwResize},
#line 283 "CSSValueKeywords.gperf"
      {"nw-resize", CSSValueNwResize},
#line 149 "CSSValueKeywords.gperf"
      {"destination-atop", CSSValueDestinationAtop},
#line 459 "CSSValueKeywords.gperf"
      {"padding-box", CSSValuePaddingBox},
#line 221 "CSSValueKeywords.gperf"
      {"lower-norwegian", CSSValueLowerNorwegian},
#line 113 "CSSValueKeywords.gperf"
      {"graytext", CSSValueGraytext},
#line 286 "CSSValueKeywords.gperf"
      {"sw-resize", CSSValueSwResize},
#line 396 "CSSValueKeywords.gperf"
      {"break-word", CSSValueBreakWord},
#line 256 "CSSValueKeywords.gperf"
      {"table-row-group", CSSValueTableRowGroup},
#line 371 "CSSValueKeywords.gperf"
      {"backwards", CSSValueBackwards},
#line 28 "CSSValueKeywords.gperf"
      {"dotted", CSSValueDotted},
#line 451 "CSSValueKeywords.gperf"
      {"rating-level-indicator", CSSValueRatingLevelIndicator},
#line 157 "CSSValueKeywords.gperf"
      {"text-top", CSSValueTextTop},
#line 417 "CSSValueKeywords.gperf"
      {"media-return-to-realtime-button", CSSValueMediaReturnToRealtimeButton},
#line 370 "CSSValueKeywords.gperf"
      {"forwards", CSSValueForwards},
#line 220 "CSSValueKeywords.gperf"
      {"hangul", CSSValueHangul},
#line 274 "CSSValueKeywords.gperf"
      {"context-menu", CSSValueContextMenu},
#line 103 "CSSValueKeywords.gperf"
      {"-webkit-activelink", CSSValueWebkitActivelink},
#line 325 "CSSValueKeywords.gperf"
      {"fixed", CSSValueFixed},
#line 119 "CSSValueKeywords.gperf"
      {"infobackground", CSSValueInfobackground},
#line 313 "CSSValueKeywords.gperf"
      {"always", CSSValueAlways},
#line 247 "CSSValueKeywords.gperf"
      {"katakana-iroha", CSSValueKatakanaIroha},
#line 414 "CSSValueKeywords.gperf"
      {"media-seek-back-button", CSSValueMediaSeekBackButton},
#line 278 "CSSValueKeywords.gperf"
      {"not-allowed", CSSValueNotAllowed},
#line 73 "CSSValueKeywords.gperf"
      {"semi-condensed", CSSValueSemiCondensed},
#line 260 "CSSValueKeywords.gperf"
      {"table-column-group", CSSValueTableColumnGroup},
#line 416 "CSSValueKeywords.gperf"
      {"media-rewind-button", CSSValueMediaRewindButton},
#line 441 "CSSValueKeywords.gperf"
      {"searchfield", CSSValueSearchfield},
#line 446 "CSSValueKeywords.gperf"
      {"textfield", CSSValueTextfield},
#line 341 "CSSValueKeywords.gperf"
      {"no-close-quote", CSSValueNoCloseQuote},
#line 350 "CSSValueKeywords.gperf"
      {"pre-wrap", CSSValuePreWrap},
#line 125 "CSSValueKeywords.gperf"
      {"threedface", CSSValueThreedface},
#line 37 "CSSValueKeywords.gperf"
      {"-webkit-mini-control", CSSValueWebkitMiniControl},
#line 433 "CSSValueKeywords.gperf"
      {"outer-spin-button", CSSValueOuterSpinButton},
#line 234 "CSSValueKeywords.gperf"
      {"tigrinya-et", CSSValueTigrinyaEt},
#line 230 "CSSValueKeywords.gperf"
      {"tigrinya-er", CSSValueTigrinyaEr},
#line 291 "CSSValueKeywords.gperf"
      {"nesw-resize", CSSValueNeswResize},
#line 38 "CSSValueKeywords.gperf"
      {"-webkit-small-control", CSSValueWebkitSmallControl},
#line 436 "CSSValueKeywords.gperf"
      {"slider-horizontal", CSSValueSliderHorizontal},
#line 246 "CSSValueKeywords.gperf"
      {"hiragana-iroha", CSSValueHiraganaIroha},
#line 389 "CSSValueKeywords.gperf"
      {"discard", CSSValueDiscard},
#line 342 "CSSValueKeywords.gperf"
      {"no-open-quote", CSSValueNoOpenQuote},
#line 434 "CSSValueKeywords.gperf"
      {"progress-bar", CSSValueProgressBar},
#line 447 "CSSValueKeywords.gperf"
      {"caps-lock-indicator", CSSValueCapsLockIndicator},
#line 354 "CSSValueKeywords.gperf"
      {"show", CSSValueShow},
#line 420 "CSSValueKeywords.gperf"
      {"media-sliderthumb", CSSValueMediaSliderthumb},
#line 359 "CSSValueKeywords.gperf"
      {"-webkit-nowrap", CSSValueWebkitNowrap},
#line 168 "CSSValueKeywords.gperf"
      {"-webkit-right", CSSValueWebkitRight},
#line 431 "CSSValueKeywords.gperf"
      {"menulist-textfield", CSSValueMenulistTextfield},
#line 421 "CSSValueKeywords.gperf"
      {"media-volume-slider-container", CSSValueMediaVolumeSliderContainer},
#line 135 "CSSValueKeywords.gperf"
      {"-webkit-text", CSSValueWebkitText},
#line 413 "CSSValueKeywords.gperf"
      {"media-play-button", CSSValueMediaPlayButton},
#line 425 "CSSValueKeywords.gperf"
      {"media-controls-background", CSSValueMediaControlsBackground},
#line 237 "CSSValueKeywords.gperf"
      {"ethiopic-abegede-ti-et", CSSValueEthiopicAbegedeTiEt},
#line 106 "CSSValueKeywords.gperf"
      {"appworkspace", CSSValueAppworkspace},
#line 233 "CSSValueKeywords.gperf"
      {"ethiopic-abegede-ti-er", CSSValueEthiopicAbegedeTiEr},
#line 335 "CSSValueKeywords.gperf"
      {"line-through", CSSValueLineThrough},
#line 212 "CSSValueKeywords.gperf"
      {"ethiopic-abegede-am-et", CSSValueEthiopicAbegedeAmEt},
#line 70 "CSSValueKeywords.gperf"
      {"ultra-condensed", CSSValueUltraCondensed},
#line 294 "CSSValueKeywords.gperf"
      {"row-resize", CSSValueRowResize},
#line 264 "CSSValueKeywords.gperf"
      {"-webkit-box", CSSValueWebkitBox},
#line 75 "CSSValueKeywords.gperf"
      {"expanded", CSSValueExpanded},
#line 118 "CSSValueKeywords.gperf"
      {"inactivecaptiontext", CSSValueInactivecaptiontext},
#line 407 "CSSValueKeywords.gperf"
      {"input-speech-button", CSSValueInputSpeechButton},
#line 219 "CSSValueKeywords.gperf"
      {"hangul-consonant", CSSValueHangulConsonant},
#line 114 "CSSValueKeywords.gperf"
      {"highlight", CSSValueHighlight},
#line 204 "CSSValueKeywords.gperf"
      {"upper-alpha", CSSValueUpperAlpha},
#line 64 "CSSValueKeywords.gperf"
      {"xx-large", CSSValueXxLarge},
#line 490 "CSSValueKeywords.gperf"
      {"maximized", CSSValueMaximized},
#line 483 "CSSValueKeywords.gperf"
      {"subpixel-antialiased", CSSValueSubpixelAntialiased},
#line 58 "CSSValueKeywords.gperf"
      {"xx-small", CSSValueXxSmall},
#line 485 "CSSValueKeywords.gperf"
      {"optimizelegibility", CSSValueOptimizelegibility},
#line 110 "CSSValueKeywords.gperf"
      {"buttonshadow", CSSValueButtonshadow},
#line 394 "CSSValueKeywords.gperf"
      {"skip-white-space", CSSValueSkipWhiteSpace},
#line 279 "CSSValueKeywords.gperf"
      {"-webkit-zoom-in", CSSValueWebkitZoomIn},
#line 415 "CSSValueKeywords.gperf"
      {"media-seek-forward-button", CSSValueMediaSeekForwardButton},
#line 367 "CSSValueKeywords.gperf"
      {"block-axis", CSSValueBlockAxis},
#line 202 "CSSValueKeywords.gperf"
      {"lower-alpha", CSSValueLowerAlpha},
#line 435 "CSSValueKeywords.gperf"
      {"progress-bar-value", CSSValueProgressBarValue},
#line 484 "CSSValueKeywords.gperf"
      {"optimizespeed", CSSValueOptimizespeed},
#line 265 "CSSValueKeywords.gperf"
      {"-webkit-inline-box", CSSValueWebkitInlineBox},
#line 132 "CSSValueKeywords.gperf"
      {"-webkit-focus-ring-color", CSSValueWebkitFocusRingColor},
#line 423 "CSSValueKeywords.gperf"
      {"media-volume-sliderthumb", CSSValueMediaVolumeSliderthumb},
#line 280 "CSSValueKeywords.gperf"
      {"-webkit-zoom-out", CSSValueWebkitZoomOut},
#line 218 "CSSValueKeywords.gperf"
      {"ethiopic-abegede-gez", CSSValueEthiopicAbegedeGez},
#line 424 "CSSValueKeywords.gperf"
      {"media-volume-slider-mute-button", CSSValueMediaVolumeSliderMuteButton},
#line 398 "CSSValueKeywords.gperf"
      {"after-white-space", CSSValueAfterWhiteSpace},
#line 214 "CSSValueKeywords.gperf"
      {"cjk-heavenly-stem", CSSValueCjkHeavenlyStem},
#line 448 "CSSValueKeywords.gperf"
      {"relevancy-level-indicator", CSSValueRelevancyLevelIndicator},
#line 229 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-tig", CSSValueEthiopicHalehameTig},
#line 243 "CSSValueKeywords.gperf"
      {"cjk-ideographic", CSSValueCjkIdeographic},
#line 257 "CSSValueKeywords.gperf"
      {"table-header-group", CSSValueTableHeaderGroup},
#line 399 "CSSValueKeywords.gperf"
      {"checkbox", CSSValueCheckbox},
#line 83 "CSSValueKeywords.gperf"
      {"-webkit-body", CSSValueWebkitBody},
#line 71 "CSSValueKeywords.gperf"
      {"extra-condensed", CSSValueExtraCondensed},
#line 390 "CSSValueKeywords.gperf"
      {"dot-dash", CSSValueDotDash},
#line 74 "CSSValueKeywords.gperf"
      {"semi-expanded", CSSValueSemiExpanded},
#line 236 "CSSValueKeywords.gperf"
      {"tigrinya-et-abegede", CSSValueTigrinyaEtAbegede},
#line 232 "CSSValueKeywords.gperf"
      {"tigrinya-er-abegede", CSSValueTigrinyaErAbegede},
#line 444 "CSSValueKeywords.gperf"
      {"searchfield-results-button", CSSValueSearchfieldResultsButton},
#line 427 "CSSValueKeywords.gperf"
      {"media-time-remaining-display", CSSValueMediaTimeRemainingDisplay},
#line 438 "CSSValueKeywords.gperf"
      {"sliderthumb-horizontal", CSSValueSliderthumbHorizontal},
#line 109 "CSSValueKeywords.gperf"
      {"buttonhighlight", CSSValueButtonhighlight},
#line 442 "CSSValueKeywords.gperf"
      {"searchfield-decoration", CSSValueSearchfieldDecoration},
#line 445 "CSSValueKeywords.gperf"
      {"searchfield-cancel-button", CSSValueSearchfieldCancelButton},
#line 235 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-ti-et", CSSValueEthiopicHalehameTiEt},
#line 231 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-ti-er", CSSValueEthiopicHalehameTiEr},
#line 418 "CSSValueKeywords.gperf"
      {"media-toggle-closed-captions-button", CSSValueMediaToggleClosedCaptionsButton},
#line 207 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-aa-et", CSSValueEthiopicHalehameAaEt},
#line 208 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-aa-er", CSSValueEthiopicHalehameAaEr},
#line 210 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-am-et", CSSValueEthiopicHalehameAmEt},
#line 227 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-so-et", CSSValueEthiopicHalehameSoEt},
#line 223 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-om-et", CSSValueEthiopicHalehameOmEt},
#line 161 "CSSValueKeywords.gperf"
      {"-webkit-baseline-middle", CSSValueWebkitBaselineMiddle},
#line 115 "CSSValueKeywords.gperf"
      {"highlighttext", CSSValueHighlighttext},
#line 426 "CSSValueKeywords.gperf"
      {"media-current-time-display", CSSValueMediaCurrentTimeDisplay},
#line 128 "CSSValueKeywords.gperf"
      {"threedshadow", CSSValueThreedshadow},
#line 77 "CSSValueKeywords.gperf"
      {"ultra-expanded", CSSValueUltraExpanded},
#line 382 "CSSValueKeywords.gperf"
      {"read-write-plaintext-only", CSSValueReadWritePlaintextOnly},
#line 176 "CSSValueKeywords.gperf"
      {"decimal-leading-zero", CSSValueDecimalLeadingZero},
#line 216 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-gez", CSSValueEthiopicHalehameGez},
#line 443 "CSSValueKeywords.gperf"
      {"searchfield-results-decoration", CSSValueSearchfieldResultsDecoration},
#line 198 "CSSValueKeywords.gperf"
      {"upper-hexadecimal", CSSValueUpperHexadecimal},
#line 213 "CSSValueKeywords.gperf"
      {"cjk-earthly-branch", CSSValueCjkEarthlyBranch},
#line 225 "CSSValueKeywords.gperf"
      {"ethiopic-halehame-sid-et", CSSValueEthiopicHalehameSidEt},
#line 186 "CSSValueKeywords.gperf"
      {"lower-hexadecimal", CSSValueLowerHexadecimal},
#line 391 "CSSValueKeywords.gperf"
      {"dot-dot-dash", CSSValueDotDotDash},
#line 126 "CSSValueKeywords.gperf"
      {"threedhighlight", CSSValueThreedhighlight},
#line 76 "CSSValueKeywords.gperf"
      {"extra-expanded", CSSValueExtraExpanded},
#line 127 "CSSValueKeywords.gperf"
      {"threedlightshadow", CSSValueThreedlightshadow},
#line 65 "CSSValueKeywords.gperf"
      {"-webkit-xxx-large", CSSValueWebkitXxxLarge},
#line 124 "CSSValueKeywords.gperf"
      {"threeddarkshadow", CSSValueThreeddarkshadow},
#line 449 "CSSValueKeywords.gperf"
      {"continuous-capacity-level-indicator", CSSValueContinuousCapacityLevelIndicator},
#line 450 "CSSValueKeywords.gperf"
      {"discrete-capacity-level-indicator", CSSValueDiscreteCapacityLevelIndicator}
    };

  static const short lookup[] =
    {
       -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,
        1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
        2,  -1,  -1,  -1,  -1,   3,  -1,  -1,  -1,  -1,
        4,  -1,  -1,  -1,  -1,   5,  -1,  -1,  -1,  -1,
        6,  -1,  -1,  -1,  -1,   7,  -1,  -1,  -1,  -1,
        8,  -1,  -1,  -1,  -1,   9,  10,  -1,  -1,  -1,
       11,  12,  13,  -1,  -1,  14,  -1,  -1,  -1,  -1,
       15,  -1,  -1,  -1,  -1,  16,  17,  -1,  -1,  -1,
       18,  -1,  -1,  -1,  -1,  19,  20,  -1,  -1,  -1,
       21,  -1,  -1,  -1,  -1,  22,  -1,  -1,  -1,  -1,
       23,  -1,  -1,  -1,  -1,  24,  -1,  -1,  -1,  -1,
       -1,  25,  -1,  -1,  -1,  26,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  27,  -1,  -1,  -1,
       28,  -1,  -1,  -1,  -1,  29,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  30,  -1,  -1,  -1,  -1,
       31,  32,  -1,  -1,  -1,  33,  -1,  -1,  -1,  -1,
       -1,  34,  35,  -1,  -1,  -1,  -1,  36,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       37,  38,  -1,  -1,  -1,  39,  40,  -1,  -1,  -1,
       41,  42,  -1,  -1,  -1,  -1,  43,  44,  -1,  -1,
       45,  -1,  -1,  -1,  -1,  46,  -1,  -1,  -1,  -1,
       47,  -1,  48,  -1,  -1,  49,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  50,  -1,  -1,  -1,  -1,
       51,  -1,  -1,  -1,  -1,  52,  -1,  -1,  -1,  -1,
       53,  54,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  55,  -1,  -1,  56,  57,  -1,  -1,  -1,
       58,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       59,  -1,  -1,  -1,  -1,  60,  61,  -1,  -1,  -1,
       62,  -1,  -1,  -1,  -1,  63,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  64,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  65,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       66,  67,  -1,  -1,  -1,  68,  69,  -1,  -1,  -1,
       -1,  70,  -1,  -1,  -1,  71,  -1,  -1,  -1,  -1,
       -1,  -1,  72,  -1,  -1,  73,  74,  -1,  -1,  -1,
       -1,  75,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  76,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  77,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  78,  -1,  -1,  -1,
       -1,  -1,  79,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       80,  -1,  -1,  -1,  -1,  81,  -1,  -1,  -1,  -1,
       -1,  -1,  82,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  83,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       84,  -1,  85,  -1,  -1,  86,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  87,  -1,  -1,  -1,  -1,
       88,  89,  -1,  -1,  -1,  90,  91,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  92,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  93,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  94,  -1,  -1,  -1,  -1,
       95,  -1,  -1,  -1,  -1,  -1,  96,  -1,  -1,  -1,
       97,  98,  -1,  -1,  -1,  99, 100,  -1,  -1,  -1,
      101,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      102, 103,  -1,  -1,  -1, 104,  -1,  -1,  -1,  -1,
      105, 106,  -1,  -1,  -1, 107, 108,  -1,  -1,  -1,
      109, 110,  -1,  -1,  -1,  -1, 111,  -1,  -1,  -1,
      112, 113,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 114,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 115,  -1,  -1,  -1,  -1, 116,  -1,  -1,  -1,
      117, 118, 119,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      120,  -1,  -1,  -1,  -1,  -1, 121,  -1,  -1,  -1,
       -1,  -1, 122,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 123,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      124,  -1,  -1,  -1,  -1, 125, 126,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 127, 128,  -1,  -1,  -1,
       -1,  -1, 129,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 130,  -1,  -1,  -1,  -1,
      131,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      132,  -1,  -1,  -1,  -1, 133, 134,  -1,  -1,  -1,
       -1,  -1, 135,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      136,  -1,  -1,  -1,  -1,  -1, 137, 138,  -1,  -1,
       -1, 139,  -1,  -1,  -1, 140, 141,  -1,  -1,  -1,
      142,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      143,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 144,  -1,  -1,  -1,  -1,
      145,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 146,  -1,  -1,  -1, 147,  -1,  -1,  -1,  -1,
      148,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 149,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      150,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 151,  -1,  -1,  -1,  -1,
      152, 153, 154,  -1,  -1, 155,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 156, 157,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 158, 159,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      160,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 161,  -1,  -1,  -1, 162, 163,  -1,  -1,  -1,
      164,  -1,  -1,  -1,  -1, 165, 166,  -1,  -1,  -1,
      167, 168,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      169, 170,  -1,  -1,  -1, 171, 172,  -1,  -1,  -1,
      173,  -1,  -1,  -1,  -1, 174,  -1,  -1,  -1,  -1,
      175, 176,  -1,  -1,  -1, 177,  -1,  -1,  -1,  -1,
      178, 179,  -1,  -1,  -1, 180,  -1,  -1,  -1,  -1,
       -1, 181,  -1,  -1,  -1, 182, 183,  -1,  -1,  -1,
       -1,  -1, 184,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      185,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 186,  -1,  -1,  -1, 187,  -1,  -1,  -1,  -1,
      188,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      189,  -1,  -1,  -1,  -1, 190, 191,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 192,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 193,  -1,  -1,  -1,  -1,
      194,  -1,  -1,  -1,  -1, 195,  -1,  -1,  -1,  -1,
      196, 197,  -1,  -1,  -1,  -1, 198,  -1,  -1,  -1,
      199,  -1,  -1,  -1,  -1, 200,  -1,  -1,  -1,  -1,
      201,  -1,  -1,  -1,  -1,  -1,  -1, 202,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 203,  -1,  -1,  -1,  -1,
      204,  -1,  -1,  -1,  -1, 205, 206,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 207,  -1,  -1,  -1,
      208,  -1,  -1,  -1,  -1,  -1, 209,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 210,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 211,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 212,  -1,  -1,  -1,
      213, 214,  -1,  -1,  -1,  -1, 215,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 216,  -1,  -1,  -1,
      217,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 218,  -1,  -1,  -1, 219, 220,  -1,  -1,  -1,
       -1, 221,  -1,  -1,  -1,  -1,  -1, 222,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 223,  -1,  -1,  -1, 224,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 225,  -1,  -1,
       -1, 226,  -1,  -1,  -1, 227, 228,  -1,  -1,  -1,
      229,  -1, 230,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      231, 232,  -1,  -1,  -1, 233,  -1,  -1,  -1,  -1,
      234,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      235,  -1,  -1,  -1,  -1,  -1,  -1, 236,  -1,  -1,
      237, 238,  -1,  -1,  -1, 239,  -1,  -1,  -1,  -1,
       -1,  -1, 240,  -1,  -1, 241,  -1,  -1,  -1,  -1,
      242,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 243,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 244,  -1,  -1,  -1,
       -1, 245,  -1,  -1,  -1, 246,  -1,  -1,  -1,  -1,
       -1, 247, 248,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 249,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 250,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 251,  -1,  -1,  -1,  -1,
      252, 253,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      254, 255,  -1,  -1,  -1,  -1,  -1, 256,  -1,  -1,
      257, 258,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      259, 260,  -1, 261,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 262,  -1,  -1,
       -1, 263,  -1,  -1,  -1, 264,  -1,  -1,  -1,  -1,
       -1, 265,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      266,  -1,  -1,  -1,  -1, 267,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 268, 269,  -1,  -1,  -1,
       -1,  -1, 270,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 271,  -1,  -1,  -1, 272,  -1,  -1,  -1,  -1,
       -1, 273, 274,  -1,  -1,  -1, 275,  -1,  -1,  -1,
       -1, 276,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 277, 278,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 279, 280,  -1,  -1,
       -1, 281,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 282,  -1,  -1,  -1,  -1,
      283,  -1,  -1,  -1,  -1, 284, 285,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 286,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      287,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      288,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 289, 290, 291,  -1,  -1,
      292,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 293,  -1,  -1,  -1, 294,  -1,  -1,  -1,  -1,
       -1,  -1, 295,  -1,  -1, 296,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 297, 298,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 299,  -1,  -1,  -1,  -1,
       -1, 300,  -1,  -1,  -1, 301, 302,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 303,  -1,
       -1, 304,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 305,  -1,  -1,
       -1, 306,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 307, 308,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 309,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 310,  -1,  -1,  -1, 311, 312,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 313, 314,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 315,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 316,  -1,  -1,  -1,  -1, 317,  -1,  -1,  -1,
      318,  -1, 319,  -1,  -1,  -1, 320,  -1,  -1,  -1,
       -1, 321,  -1,  -1,  -1, 322, 323,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 324,  -1,  -1,  -1,
      325, 326,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 327, 328,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 329, 330,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 331,  -1,  -1,  -1,  -1,
       -1,  -1, 332,  -1,  -1, 333,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 334, 335,  -1,  -1,
       -1, 336,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      337,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 338,  -1,  -1,  -1, 339,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 340,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 341,  -1,  -1,  -1,
      342, 343, 344,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 345,  -1,  -1,  -1,  -1, 346,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 347, 348,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 349,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 350,  -1,  -1, 351,  -1,
       -1, 352,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 353,  -1,  -1,  -1, 354,  -1,  -1,  -1,  -1,
      355,  -1,  -1,  -1,  -1, 356,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 357,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 358,  -1,  -1,  -1,  -1,  -1, 359,  -1,  -1,
       -1, 360,  -1,  -1,  -1, 361,  -1,  -1,  -1,  -1,
       -1, 362,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 363,  -1,  -1,  -1,
       -1, 364,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 365, 366,  -1,  -1,
      367,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 368,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 369,  -1,  -1,  -1,
       -1, 370,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 371, 372,  -1,  -1,  -1,
      373,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 374,  -1,  -1,  -1,
       -1, 375,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      376,  -1,  -1,  -1,  -1,  -1, 377,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 378,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 379,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 380,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 381,  -1,  -1,  -1, 382,  -1,  -1,  -1,  -1,
       -1, 383,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      384,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 385,  -1,  -1,  -1,  -1,  -1, 386,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 387,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 388, 389,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 390, 391,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 392,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 393,  -1,  -1,  -1, 394, 395,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 396,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 397,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 398,  -1,  -1,  -1,  -1,
      399, 400,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 401,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 402, 403,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 404,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 405,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 406,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 407,  -1,  -1,  -1,
       -1,  -1, 408,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 409,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      410,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 411,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 412,  -1,  -1,  -1,
       -1,  -1,  -1, 413,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 414,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 415,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 416,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      417,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 418,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 419,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 420,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 421,  -1,  -1,
       -1,  -1, 422,  -1,  -1,  -1, 423,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 424,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 425,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 426,  -1,  -1,  -1,
       -1,  -1,  -1, 427,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 428,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 429,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 430,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 431,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 432,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 433,  -1,  -1,
      434,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      435,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 436, 437,  -1,  -1,
       -1,  -1, 438,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      439,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1, 440,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 441,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 442,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      443,  -1,  -1,  -1,  -1, 444,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 445,  -1,  -1,  -1,
       -1, 446,  -1, 447,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 448,  -1,  -1,  -1,  -1, 449,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 450,  -1,  -1,  -1,  -1, 451,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 452,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 453,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 454,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 455,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 456,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      457,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 458,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 459,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 460,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      461,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 462, 463,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 464,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      465,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      466,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 467,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 468,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 469,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 470,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 471,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 472,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 473
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = value_hash_function (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = value_word_list[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &value_word_list[index];
            }
        }
    }
  return 0;
}
#line 494 "CSSValueKeywords.gperf"

static const char * const valueList[] = {
"",
"inherit", 
"initial", 
"none", 
"hidden", 
"inset", 
"groove", 
"ridge", 
"outset", 
"dotted", 
"dashed", 
"solid", 
"double", 
"caption", 
"icon", 
"menu", 
"message-box", 
"small-caption", 
"-webkit-mini-control", 
"-webkit-small-control", 
"-webkit-control", 
"status-bar", 
"italic", 
"oblique", 
"all", 
"small-caps", 
"normal", 
"bold", 
"bolder", 
"lighter", 
"100", 
"200", 
"300", 
"400", 
"500", 
"600", 
"700", 
"800", 
"900", 
"xx-small", 
"x-small", 
"small", 
"medium", 
"large", 
"x-large", 
"xx-large", 
"-webkit-xxx-large", 
"smaller", 
"larger", 
"wider", 
"narrower", 
"ultra-condensed", 
"extra-condensed", 
"condensed", 
"semi-condensed", 
"semi-expanded", 
"expanded", 
"extra-expanded", 
"ultra-expanded", 
"serif", 
"sans-serif", 
"cursive", 
"fantasy", 
"monospace", 
"-webkit-body", 
"aqua", 
"black", 
"blue", 
"fuchsia", 
"gray", 
"green", 
"lime", 
"maroon", 
"navy", 
"olive", 
"orange", 
"purple", 
"red", 
"silver", 
"teal", 
"white", 
"yellow", 
"transparent", 
"-webkit-link", 
"-webkit-activelink", 
"activeborder", 
"activecaption", 
"appworkspace", 
"background", 
"buttonface", 
"buttonhighlight", 
"buttonshadow", 
"buttontext", 
"captiontext", 
"graytext", 
"highlight", 
"highlighttext", 
"inactiveborder", 
"inactivecaption", 
"inactivecaptiontext", 
"infobackground", 
"infotext", 
"match", 
"menutext", 
"scrollbar", 
"threeddarkshadow", 
"threedface", 
"threedhighlight", 
"threedlightshadow", 
"threedshadow", 
"window", 
"windowframe", 
"windowtext", 
"-webkit-focus-ring-color", 
"currentcolor", 
"grey", 
"-webkit-text", 
"repeat", 
"repeat-x", 
"repeat-y", 
"no-repeat", 
"clear", 
"copy", 
"source-over", 
"source-in", 
"source-out", 
"source-atop", 
"destination-over", 
"destination-in", 
"destination-out", 
"destination-atop", 
"xor", 
"plus-darker", 
"plus-lighter", 
"baseline", 
"middle", 
"sub", 
"super", 
"text-top", 
"text-bottom", 
"top", 
"bottom", 
"-webkit-baseline-middle", 
"-webkit-auto", 
"left", 
"right", 
"center", 
"justify", 
"-webkit-left", 
"-webkit-right", 
"-webkit-center", 
"outside", 
"inside", 
"disc", 
"circle", 
"square", 
"decimal", 
"decimal-leading-zero", 
"arabic-indic", 
"binary", 
"bengali", 
"cambodian", 
"khmer", 
"devanagari", 
"gujarati", 
"gurmukhi", 
"kannada", 
"lower-hexadecimal", 
"lao", 
"malayalam", 
"mongolian", 
"myanmar", 
"octal", 
"oriya", 
"persian", 
"urdu", 
"telugu", 
"tibetan", 
"thai", 
"upper-hexadecimal", 
"lower-roman", 
"upper-roman", 
"lower-greek", 
"lower-alpha", 
"lower-latin", 
"upper-alpha", 
"upper-latin", 
"afar", 
"ethiopic-halehame-aa-et", 
"ethiopic-halehame-aa-er", 
"amharic", 
"ethiopic-halehame-am-et", 
"amharic-abegede", 
"ethiopic-abegede-am-et", 
"cjk-earthly-branch", 
"cjk-heavenly-stem", 
"ethiopic", 
"ethiopic-halehame-gez", 
"ethiopic-abegede", 
"ethiopic-abegede-gez", 
"hangul-consonant", 
"hangul", 
"lower-norwegian", 
"oromo", 
"ethiopic-halehame-om-et", 
"sidama", 
"ethiopic-halehame-sid-et", 
"somali", 
"ethiopic-halehame-so-et", 
"tigre", 
"ethiopic-halehame-tig", 
"tigrinya-er", 
"ethiopic-halehame-ti-er", 
"tigrinya-er-abegede", 
"ethiopic-abegede-ti-er", 
"tigrinya-et", 
"ethiopic-halehame-ti-et", 
"tigrinya-et-abegede", 
"ethiopic-abegede-ti-et", 
"upper-greek", 
"upper-norwegian", 
"hebrew", 
"armenian", 
"georgian", 
"cjk-ideographic", 
"hiragana", 
"katakana", 
"hiragana-iroha", 
"katakana-iroha", 
"inline", 
"block", 
"list-item", 
"run-in", 
"compact", 
"inline-block", 
"table", 
"inline-table", 
"table-row-group", 
"table-header-group", 
"table-footer-group", 
"table-row", 
"table-column-group", 
"table-column", 
"table-cell", 
"table-caption", 
"-webkit-box", 
"-webkit-inline-box", 
"-wap-marquee", 
"auto", 
"crosshair", 
"default", 
"pointer", 
"move", 
"vertical-text", 
"cell", 
"context-menu", 
"alias", 
"progress", 
"no-drop", 
"not-allowed", 
"-webkit-zoom-in", 
"-webkit-zoom-out", 
"e-resize", 
"ne-resize", 
"nw-resize", 
"n-resize", 
"se-resize", 
"sw-resize", 
"s-resize", 
"w-resize", 
"ew-resize", 
"ns-resize", 
"nesw-resize", 
"nwse-resize", 
"col-resize", 
"row-resize", 
"text", 
"wait", 
"help", 
"all-scroll", 
"-webkit-grab", 
"-webkit-grabbing", 
"ltr", 
"rtl", 
"capitalize", 
"uppercase", 
"lowercase", 
"visible", 
"collapse", 
"a3", 
"a4", 
"a5", 
"above", 
"absolute", 
"always", 
"avoid", 
"b4", 
"b5", 
"below", 
"bidi-override", 
"blink", 
"both", 
"close-quote", 
"crop", 
"cross", 
"embed", 
"fixed", 
"hand", 
"hide", 
"higher", 
"invert", 
"landscape", 
"ledger", 
"legal", 
"letter", 
"level", 
"line-through", 
"local", 
"loud", 
"lower", 
"-webkit-marquee", 
"mix", 
"no-close-quote", 
"no-open-quote", 
"nowrap", 
"open-quote", 
"overlay", 
"overline", 
"portrait", 
"pre", 
"pre-line", 
"pre-wrap", 
"relative", 
"scroll", 
"separate", 
"show", 
"static", 
"thick", 
"thin", 
"underline", 
"-webkit-nowrap", 
"stretch", 
"start", 
"end", 
"reverse", 
"horizontal", 
"vertical", 
"inline-axis", 
"block-axis", 
"single", 
"multiple", 
"forwards", 
"backwards", 
"ahead", 
"up", 
"down", 
"slow", 
"fast", 
"infinite", 
"slide", 
"alternate", 
"read-only", 
"read-write", 
"read-write-plaintext-only", 
"element", 
"ignore", 
"intrinsic", 
"min-intrinsic", 
"clip", 
"ellipsis", 
"discard", 
"dot-dash", 
"dot-dot-dash", 
"wave", 
"continuous", 
"skip-white-space", 
"break-all", 
"break-word", 
"space", 
"after-white-space", 
"checkbox", 
"radio", 
"push-button", 
"square-button", 
"button", 
"button-bevel", 
"default-button", 
"inner-spin-button", 
"input-speech-button", 
"list-button", 
"listbox", 
"listitem", 
"media-fullscreen-button", 
"media-mute-button", 
"media-play-button", 
"media-seek-back-button", 
"media-seek-forward-button", 
"media-rewind-button", 
"media-return-to-realtime-button", 
"media-toggle-closed-captions-button", 
"media-slider", 
"media-sliderthumb", 
"media-volume-slider-container", 
"media-volume-slider", 
"media-volume-sliderthumb", 
"media-volume-slider-mute-button", 
"media-controls-background", 
"media-current-time-display", 
"media-time-remaining-display", 
"menulist", 
"menulist-button", 
"menulist-text", 
"menulist-textfield", 
"meter", 
"outer-spin-button", 
"progress-bar", 
"progress-bar-value", 
"slider-horizontal", 
"slider-vertical", 
"sliderthumb-horizontal", 
"sliderthumb-vertical", 
"caret", 
"searchfield", 
"searchfield-decoration", 
"searchfield-results-decoration", 
"searchfield-results-button", 
"searchfield-cancel-button", 
"textfield", 
"caps-lock-indicator", 
"relevancy-level-indicator", 
"continuous-capacity-level-indicator", 
"discrete-capacity-level-indicator", 
"rating-level-indicator", 
"textarea", 
"round", 
"border", 
"border-box", 
"content", 
"content-box", 
"padding", 
"padding-box", 
"contain", 
"cover", 
"logical", 
"visual", 
"lines", 
"running", 
"paused", 
"flat", 
"preserve-3d", 
"ease", 
"linear", 
"ease-in", 
"ease-out", 
"ease-in-out", 
"document", 
"reset", 
"visiblepainted", 
"visiblefill", 
"visiblestroke", 
"painted", 
"fill", 
"stroke", 
"antialiased", 
"subpixel-antialiased", 
"optimizespeed", 
"optimizelegibility", 
"geometricprecision", 
"srgb", 
"floating", 
"fullscreen", 
"maximized", 
"minimized", 
"windowed", 
"manual", 
    0
};
const char* getValueName(unsigned short id)
{
    if (id >= numCSSValueKeywords || id <= 0)
        return 0;
    return valueList[id];
}
